config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root   'users#index'
  get    '/signup',            to: 'users#new'
  post   '/signup',            to: 'users#create'
  get    '/login',             to: 'sessions#new'
  post   '/login',             to: 'sessions#create'
  delete '/logout',            to: 'sessions#destroy'
  patch  '/users/:id/edit',    to: 'users#update'
  patch  '/users/:id/account', to: 'users#update'
  get    '/show_additionally', to: 'rooms#show_additionally'

  resources :users do
    member do
      get :followers, :matchers, :account
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new create edit update]
  resources :relationships,       only: :create
  resources :rooms,               only: %i[show create]
  resources :messages,            only: :create
end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: :following_id, dependent: :destroy
  has_many :following, through: :active_relationships
  has_many :followers, through: :passive_relationships
  has_many :chat_room_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification',
                                  foreign_key: :visitor_id, dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification',
                                   foreign_key: :visited_id, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy

  attr_accessor :remember_token, :activation_token, :reset_token
  attribute :remove_avatar, :boolean

  before_create :create_activation_digest
  before_save   :downcase_email
  before_create :default_avatar
  before_save do
    if remove_avatar
      avatar.purge
      default_avatar
    end
  end

  VALID_EMAIL_REGEX    = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]+\z/.freeze

  validates :name,
            presence: true,
            length: { maximum: 10 }

  validates :gender,
            presence: true

  validates :age,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 99 }

  validates :prefecture_code,
            presence: true

  validates :nationality,
            presence: true

  validates :email,
            presence: true,
            length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password,
            presence: true,
            length: { in: 8..30 },
            format: { with: VALID_PASSWORD_REGEX },
            allow_nil: true

  validates :bio,
            length: { maximum: 1000 }

  validates :hobby,
            length: { maximum: 50 }

  validates :job,
            length: { maximum: 50 }

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name_e)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def save_hashed_token_in_db
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def delete_hashed_token_in_db
    update_attribute(:remember_digest, nil)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def follow(other_user)
    following << other_user
    return unless other_user.follow_notification

    Relationship.send_notification_email(other_user, self)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def matching_users
    User.where(id: passive_relationships.select(:follower_id))
        .where(id: active_relationships.select(:following_id))
  end

  def matching?(other_user)
    following?(other_user) && other_user.following?(self)
  end

  def template
    ApplicationController.renderer.render partial: 'messages/message',
                                          locals: { message: self }
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ?', current_user.id, id, 'follow'])
    return unless temp.blank?

    notification = current_user.active_notifications.new(visited_id: id, action: 'follow')
    notification.save if notification.valid?
  end

  def chat_room?(current_user)
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: id).map(&:chat_room).first
    chat_room.present?
  end

  def show_chat_room(current_user)
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: id).map(&:chat_room).first
    chat_room.id
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def default_avatar
    avatar.attach(io: File.open(Rails.root.join('app/assets/images/default_avatar.png')),
                  filename: 'default_avatar.png', content_type: 'img/png')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update destroy followers]
  before_action :correct_user,   only: %i[edit update]
  before_action :admin_user,     only: [:destroy]

  def index
    query = params[:q]
    search_history = { value: params[:q] }
    if logged_in?
      query ||= cookies[:recent_search_history].to_s
      cookies[:recent_search_history] = search_history if params[:q].present?
      @q = User.ransack(query)
      @users = @q.result.where.not(id: current_user.id, activated: false).with_attached_avatar.page(params[:page]).per(40)
    else
      @q = User.ransack(query)
      @users = @q.result.where(activated: true).with_attached_avatar.page(params[:page]).per(40)
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    path = Rails.application.routes.recognize_path(request.referer)
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Update successful!'
      if path[:controller] == 'users' && path[:action] == 'edit'
        redirect_to @user
      elsif path[:controller] == 'users' && path[:action] == 'account'
        redirect_to root_url
      end
    else
      if path[:controller] == 'users' && path[:action] == 'edit'
        render 'edit'
      elsif path[:controller] == 'users' && path[:action] == 'account'
        render 'account'
      end
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'Account deleted'
    redirect_to users_url
  end

  def followers
    @title = 'Friend Request'
    @user  = current_user
    @users = @user.followers
    notifications = @user.passive_notifications.where(action: 'follow', checked: false)
    notifications.update(checked: true)
    render 'show_follow'
  end

  def matchers
    @title = 'Matching'
    @users = current_user.matching_users
    render 'show_match'
  end

  def account
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :gender, :age, :prefecture_code,
                                 :nationality, :bio, :hobby, :job, :status, :email,
                                 :password, :password_confirmation,
                                 :remove_avatar, :follow_notification, :message_notification)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user.admin? || current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.slim
#follow_form
  - if current_user.matching?(@user)
    .matching
      | Matching!
  - elsif current_user.following?(@user)
    button.btn.btn-secondary.btn-lg[disabled]
      | Requested
  - else
    = form_with(model: current_user.active_relationships.build) do |f|
      = f.hidden_field :following_id, value: @user.id
      = f.submit "Follow", class: "btn btn-primary btn-lg", id: "follow-btn", data: { confirm: "You sure?" }

app/views/users/_search_modal.html.slim
#exampleModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        h2#exampleModalLabel.modal-title
          | Search
        button.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
      .modal-body
        = search_form_for @q do |f|
          .form-group
            = f.label :gender
            br
            = f.radio_button :gender_eq, '', { checked: true }
            = label :gender, "unspecified", value: '', class: "value-label"
            = f.radio_button :gender_eq, :male
            = f.label :gender, "male", value: :male, class: "value-label"
            = f.radio_button :gender_eq, :female
            = f.label :gender, "female", value: :female, class: "value-label"
          .form-group
            = f.label :age
            .age-range
              = f.text_field :age_gteq, class: "form-control text-form age-gteq"
              span
                | 〜
              = f.text_field :age_lteq, class: "form-control text-form age-lteq"
          .form-group
            = f.label :prefecture_code, "Area"
            = f.collection_select :prefecture_code_eq, JpPrefecture::Prefecture.all, :code, :name_e, include_blank: ""
          .form-group
            = f.label :nationality
            = f.collection_select :nationality_eq, Country.all.sort_by(&:name), :name, :name, include_blank: ""
          = f.submit "Search", class: "btn btn-primary btn-lg"

app/views/users/account.html.slim
- provide(:title, "Edit Account")
.row
  .col-md-6.offset-md-3.edit-account-block
    h1.page-title
      | Edit Account
    = form_with(model: @user, url: account_user_path(@user), local: true) do |f|
      = render 'shared/error_messages'
      .form-group
        = f.label :email
        = f.email_field :email, class: "form-control text-form"
      .form-group
        = f.label :password
        = f.password_field :password, class: "form-control text-form", placeholder: "* must include uppercase, lowercase, and number"
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: "form-control text-form"
      .form-group.notification-form
        = f.label :follow_notification
        = f.check_box :follow_notification, class: "check-box"
      .form-group.notification-form
        = f.label :message_notification
        = f.check_box :message_notification, class: "check-box"
      = f.submit "Update Account", class: "btn btn-primary btn-lg"
    hr
    = button_to "Delete Account", user_path(current_user), method: :delete, 
            data: { confirm: "You sure?" }, class: "btn btn-danger btn-lg"

app/views/users/edit.html.slim
- provide(:title, "Edit Profile")
.row
  .col-md-6.offset-md-3.edit-profile-block
    h1.page-title
      | Edit Profile
    = form_with(model: @user, url: edit_user_path(@user), local: true) do |f|
      = render 'shared/error_messages'
      .form-group
        .avatar-form
          = f.label :avatar do
            = image_tag \
              @user.avatar, class: "avatar", id: "avatar_prev"
            = f.file_field :avatar
        .remove-avatar-form
          = f.check_box :remove_avatar, class: "check-box"
          = f.label :remove_avatar
      .form-group
        = f.label :name, class: "attr-label"
        = f.text_field :name, class: "form-control text-form"
      .form-group
        = f.label :gender, class: "attr-label"
        br
        = f.radio_button :gender, :male, class: "radio-btn"
        = f.label :gender, "male", value: :male, class: "value-label"
        = f.radio_button :gender, :female, class: "radio-btn"
        = f.label :gender, "female", value: :female, class: "value-label"
      .form-group
        = f.label :age, class: "attr-label"
        = f.text_field :age, class: "form-control text-form"
      .form-group
        = f.label :prefecture_code, "Area", class: "attr-label"
        br
        = f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name_e, include_blank: ""
      .form-group
        = f.label :nationality, class: "attr-label"
        br
        = f.collection_select :nationality, Country.all.sort_by(&:name), :name, :name, include_blank: ""
      .form-group
        = f.label :bio, class: "attr-label"
        = f.text_area :bio, size: "100x10", class: "form-control textarea-form"
      .form-group
        = f.label :hobby, class: "attr-label"
        = f.text_field :hobby, class: "form-control text-form"
      .form-group
        = f.label :job, class: "attr-label"
        = f.text_field :job, class: "form-control text-form"
      .form-group
        = f.label :status, class: "attr-label"
        br
        = f.radio_button :status, :single, class: "radio-btn"
        = f.label :status, "single", value: :single, class: "value-label"
        = f.radio_button :status, :married, class: "radio-btn"
        = f.label :status, "married", value: :married, class: "value-label"
      = f.submit "Update Profile", class: "btn btn-primary btn-lg"

app/views/users/index.html.slim
- provide(:title, "Users")
.users-index-block
  button.btn.btn-primary.btn-lg.search-btn[type="button" data-toggle="modal" data-target="#exampleModal"]
    |  Search 
  = render 'search_modal'
  .top-pagination
    = paginate @users
  .users-index
    .row
      - @users.each do |user|
        .col-md-3
          .card
            = link_to user, class: "card-body" do
              = image_tag user.avatar, class: "avatar"
              br
              span.name
                = user.name 
              span.flag
                = Country.find_country_by_name(user.nationality).emoji_flag
              span.age
                = user.age
              span.gender
                - if user.gender == "male"
                  | M
                - else
                  | F
              br
              span.prefecture
                = user.prefecture_name
            - if logged_in?
              - if current_user.admin? && !current_user?(user)
                = link_to "delete", user, method: :delete, class: "delete",
                                    data: { confirm: "You sure?" }
  = paginate @users

app/views/users/new.html.slim
- provide(:title, "Sign up")
.row
  .col-md-6.offset-md-3.signup-block
    h1.page-title
      | Sign up
    = form_with(model: @user, url: signup_path, local: true) do |f|
      = render "shared/error_messages"
      .form-group
        = f.text_field :name, class: "form-control text-form", placeholder: "user name  * less than equal 10"
      .form-group
        = f.radio_button :gender, :male, class: "radio-btn"
        = f.label :gender, "male", value: :male, class: "value-label"
        = f.radio_button :gender, :female, class: "radio-btn"
        = f.label :gender, "female", value: :female, class: "value-label"
      .form-group
        = f.text_field :age, class: "form-control text-form", placeholder: "age"
      .form-group
        = f.label :prefecture_code, "Area"
        br
        = f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name_e, include_blank: ""
      .form-group
        = f.label :nationality
        = f.collection_select :nationality, Country.all.sort_by(&:name), :name, :name, include_blank: ""
      .form-group
        = f.email_field :email, class: "form-control text-form", placeholder: "email"
      .form-group
        = f.password_field :password, class: "form-control text-form", placeholder: "password  * must include uppercase, lowercase, and number"
      .form-group
        = f.password_field :password_confirmation, class: "form-control text-form", placeholder: "password confirmation"
      = f.submit "Sign up", class: "btn btn-success btn-lg"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  .col-md-6.offset-md-3.profile-block
    .avatar-block
      = image_tag @user.avatar, class: "avatar"
    .name-block
      h1.name
        = @user.name
      div
        span.age
          = @user.age
        span.gender
          - if @user.gender == "male"
            | M
          - else 
            | F
    .nationality
      = @user.nationality
      = Country.find_country_by_name(@user.nationality).emoji_flag
    .prefecture
      = @user.prefecture_name
    - if logged_in?
      - if current_user?(@user)
        = link_to "Edit profile", edit_user_path(@user), class: "btn btn-info btn-lg"
      - else
        = render 'follow_form'
    h2.bio
      | Bio
    .answer-field-bio
      = simple_format(h @user.bio)
    h2.hobby
      | Hobby 
    .answer-field
      = @user.hobby
    h2.job
      | Job 
    .answer-field
      = @user.job
    h2.status
      | Status 
    .answer-field
      = @user.status

app/views/users/show_follow.html.slim
- provide(:title, @title)
.followers-block
  - @users.each do |user|
    - if !@user.matching?(user)
      .card.follower-card
        = link_to user, class: "card-body" do
          .avatar-img
            = image_tag \
              user.avatar, class: "avatar"
          .follower-info
            span.name
              = user.name
            = Country.find_country_by_name(user.nationality).emoji_flag
            span.age
              = user.age
            span.gender
              - if user.gender == "male"
                | M
              - else
                | F
            br
            span.prefecture
              = user.prefecture_name

app/views/users/show_match.html.slim
- provide(:title, @title)
.matchers-block
  - if !@users.empty?
    - @users.each do |user|
      .card.matcher-card
        = link_to user, class: "card-body" do
          .avatar-img
            = image_tag \
              user.avatar, class: "avatar"
          .matcher-info
            span.name
              = user.name
            = Country.find_country_by_name(user.nationality).emoji_flag
            span.age
              = user.age
            span.gender
              - if user.gender == "male"
                | M
              - else
                | F
            br
            span.prefecture
              = user.prefecture_name
          - if user.chat_room?(current_user) && unchecked_room_notifications(user.show_chat_room(current_user)).any?
            i.n-circle.fas.fa-circle
        .card-footer
          = form_with url: rooms_path do |f|
            = f.hidden_field :user_id, value: user.id
            = f.submit "Chat", class: "btn btn-success btn-lg"
  - else
    .jumbotron
      | Not yet matched