config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root   'users#index'
  get    '/signup',            to: 'users#new'
  post   '/signup',            to: 'users#create'
  get    '/login',             to: 'sessions#new'
  post   '/login',             to: 'sessions#create'
  delete '/logout',            to: 'sessions#destroy'
  patch  '/users/:id/edit',    to: 'users#update'
  patch  '/users/:id/account', to: 'users#update'
  get    '/show_additionally', to: 'rooms#show_additionally'

  resources :users do
    member do
      get :followers, :matchers, :account
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new create edit update]
  resources :relationships,       only: :create
  resources :rooms,               only: %i[show create]
  resources :messages,            only: :create
end

app/views/layouts/_follower_button.html.slim
li
  = link_to followers_user_path(current_user) do
    - if unchecked_follow_notifications.any?
      i.header-icon.far.fa-thumbs-up.fa-3x
      i.n-circle.fas.fa-circle
    - else
      i.header-icon.far.fa-thumbs-up.fa-3x

app/views/layouts/_header.html.slim
header.navbar
  -if !logged_in?
    = link_to root_path, class: "root-link"
      = image_tag "logo.png", class: "logo"
    = link_to "Sign up", signup_path, class: "btn btn-success btn-lg"
    = link_to "Log in", login_path, class: "btn btn-primary btn-lg"
  -else
    nav
      ul.nav-list
        = render 'layouts/search_button'
        = render 'layouts/follower_button'
        = render 'layouts/matching_user_button'
        = render 'layouts/profile_button'
        = render 'layouts/setting_button'

app/views/layouts/_matching_user_button.html.slim
li
  = link_to matchers_user_path(current_user) do
    - if unchecked_message_notifications.any?
      i.header-icon.far.fa-comments.fa-3x
      i.n-circle.fas.fa-circle
    - else
      i.header-icon.far.fa-comments.fa-3x

app/views/layouts/_profile_button.html.slim
li
  = link_to user_path(current_user) do
    i.header-icon.far.fa-user.fa-3x

app/views/layouts/_search_button.html.slim
li
  = link_to users_path do
    i.header-icon.fas.fa-search.fa-3x

app/views/layouts/_setting_button.html.slim
li.dropdown
  a href="#" data-toggle="dropdown"
    i.header-icon.fas.fa-cog.fa-3x
  ul.dropdown-menu 
    li.dropdown-item
      = link_to "Account", account_user_path(current_user)
    li.dropdown-item
      = link_to "Log out", logout_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container.base-container
      - flash.each do |message_type, message|
        = tag.div message, class: "alert alert-#{message_type}"
      = yield
      /= debug(params) if Rails.env.development?